version: 0.9
os: linux
files:
  - source: /
    destination: /var/app/current
permissions:
  - object: /var/app/current
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file